name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop]



jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Run linters
        run: |
          bin/rubocop --parallel
          bin/stylelint
          bin/prettier
          bin/eslint

      - name: Run security checks
        run: |
          bin/bundler-audit --update
          bin/brakeman -q -w2

  tests:
    name: Test Harnesses
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: awspost_test
          POSTGRES_PASSWORD: postgres
        ports: ['5500:5432']
        #options: >-
        #  --health-cmd pg_isready
        #  --health-interval 10ms
        #  --health-timeout 500ms
        #  --health-retries 15
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 19.4.0
          cache: yarn

      - name: Install yarn packages
        run: |
          yarn install --pure-lockfile

      - name: Install Dependencies
        run: |
          gem install bundler

      - name: Install Gems
        run: |
          bundle install --jobs 4 --retry 3

      - name: Prepare Database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:prepare

      - name: Prepare environment
        run: |
          rails test:prepare

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5500/awspost_test
          REDIS_URL: redis://localhost:6379/0
          # RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rails test
