name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: awspost_test
          POSTGRES_PASSWORD: postgres
        ports: ['5500:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install Dependencies
        run: |
          gem install bundler

      - name: Install Gems
        run: |
          bundle install

      - name: Prepare Database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:prepare

      - name: Run Tests
        env:
          #DATABASE_URL: postgres://postgres:@localhost:5432/awspost_test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rails test
